In [ ]:
# Data Scaling Techniques

# Types of Data Scaling

# 01. Standardization (Z-score Normalization) (-3 to 3)(But center will be 0 ) ✅✨(Sub sa zyada ya use hota ha)
# 02. Min-Max Scaling (scale between 0 to 1) ✅
# 03. Mazimum Absolute Scaling (scale between -1 to +1) ✅
# 04. Robust Scaling (using median and IQR)(and ignore outliers) ✅✨(agr outliers ho to use kro)

In [ ]:
# Importing Libraries

import pandas as pd
import numpy as np

In [ ]:
# Now we create a sample dataset to demonstrate data scaling techniques.


data = {
    'age_years': [15, 25, 35, 45, 55],
    'Height_cm': [150, 160, 170, 180, 190],
    'weight_kg': [50, 60, 70, 80, 90]
}   
df = pd.DataFrame(data)
df.head()

   age_years  Height_cm  weight_kg
0         15        150         50
1         25        160         60
2         35        170         70
3         45        180         80
4         55        190         90

In [ ]:
# 01. Standardization (Z-score Normalization) ✅

# now we apply Standard Scaler to the dataset.
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler_values = scaler.fit_transform(df)
scaler_values

# now we convert data into pandas Dataframe

# data_frame = pd.DataFrame(scaler_values, columns=df.columns)
data_frame = pd.DataFrame(scaler_values, columns=['age','Hight','Weight'])
data_frame.head()

        age     Hight    Weight
0 -1.414214 -1.414214 -1.414214
1 -0.707107 -0.707107 -0.707107
2  0.000000  0.000000  0.000000
3  0.707107  0.707107  0.707107
4  1.414214  1.414214  1.414214

In [8]:
# 02. Min-Max Scaling (scale between 0 to 1) ✅

data = {
    'age_years': [15, 25, 35, 45, 55],
    'Height_cm': [150, 160, 170, 180, 190],
    'weight_kg': [50, 60, 70, 80, 90]
}   
df = pd.DataFrame(data)
df.head()


from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
scaler_values = scaler.fit_transform(df)
scaler_values
data_frame = pd.DataFrame(scaler_values, columns=['age','Hight','Weight'])
data_frame.head()

    age  Hight  Weight
0  0.00   0.00    0.00
1  0.25   0.25    0.25
2  0.50   0.50    0.50
3  0.75   0.75    0.75
4  1.00   1.00    1.00

In [ ]:
# 03. Mazimum Absolute Scaling  ✅

data = {
    'age_years': [15, 25, 35, 45, 55],
    'Height_cm': [150, 160, 170, 180, 190],
    'weight_kg': [50, 60, 70, 80, 90]
}   
df = pd.DataFrame(data)
df.head()

from sklearn.preprocessing import MaxAbsScaler
scaler = MaxAbsScaler()
scaler_values = scaler.fit_transform(df)
scaler_values
data_frame = pd.DataFrame(scaler_values, columns=['age','Hight','Weight'])
data_frame.head()

        age     Hight    Weight
0  0.272727  0.789474  0.555556
1  0.454545  0.842105  0.666667
2  0.636364  0.894737  0.777778
3  0.818182  0.947368  0.888889
4  1.000000  1.000000  1.000000

In [10]:

# 04. Robust Scaling (using median and IQR) ✅

data = {
    'age_years': [15, 25, 35, 45, 55],
    'Height_cm': [150, 160, 170, 180, 190],
    'weight_kg': [50, 60, 70, 80, 90]
}   
df = pd.DataFrame(data)
df.head()

from sklearn.preprocessing import RobustScaler
scaler = RobustScaler()
scaler_values = scaler.fit_transform(df)
scaler_values
data_frame = pd.DataFrame(scaler_values, columns=['age','Hight','Weight'])
data_frame.head()

   age  Hight  Weight
0 -1.0   -1.0    -1.0
1 -0.5   -0.5    -0.5
2  0.0    0.0     0.0
3  0.5    0.5     0.5
4  1.0    1.0     1.0